// <auto-generated />
using Akinel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Akinel.Infrastructure.Migrations
{
    [DbContext(typeof(AkinelDbContext))]
    [Migration("20260930100000_AddBusinessSettingsPhone2")]
    partial class AddBusinessSettingsPhone2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
